export interface CountryDef {
  code: string;
  name: string;
  dial: string;
  flag: string;
  pattern: RegExp;
  placeholder: string;
}

export const COUNTRIES: CountryDef[] = [
  {
    code: 'CI',
    name: "Côte d'Ivoire",
    dial: '+225',
    flag: '🇨🇮',
    pattern: /^\d{10}$/,
    placeholder: '07 12 34 56 78',
  },
  {
    code: 'SN',
    name: 'Sénégal',
    dial: '+221',
    flag: '🇸🇳',
    pattern: /^\d{9}$/,
    placeholder: '77 123 45 67',
  },
  {
    code: 'ML',
    name: 'Mali',
    dial: '+223',
    flag: '🇲🇱',
    pattern: /^\d{8}$/,
    placeholder: '76 12 34 56',
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    dial: '+226',
    flag: '🇧🇫',
    pattern: /^\d{8}$/,
    placeholder: '70 12 34 56',
  },
  {
    code: 'TG',
    name: 'Togo',
    dial: '+228',
    flag: '🇹🇬',
    pattern: /^\d{8}$/,
    placeholder: '90 12 34 56',
  },
  {
    code: 'BJ',
    name: 'Bénin',
    dial: '+229',
    flag: '🇧🇯',
    pattern: /^\d{8}$/,
    placeholder: '97 12 34 56',
  },
  {
    code: 'GN',
    name: 'Guinée',
    dial: '+224',
    flag: '🇬🇳',
    pattern: /^\d{9}$/,
    placeholder: '621 12 34 56',
  },
  {
    code: 'NE',
    name: 'Niger',
    dial: '+227',
    flag: '🇳🇪',
    pattern: /^\d{8}$/,
    placeholder: '96 12 34 56',
  },
  {
    code: 'GW',
    name: 'Guinée-Bissau',
    dial: '+245',
    flag: '🇬🇼',
    pattern: /^\d{7}$/,
    placeholder: '955 12 34',
  },
  {
    code: 'MR',
    name: 'Mauritanie',
    dial: '+222',
    flag: '🇲🇷',
    pattern: /^\d{8}$/,
    placeholder: '36 12 34 56',
  },
  {
    code: 'CM',
    name: 'Cameroun',
    dial: '+237',
    flag: '🇨🇲',
    pattern: /^\d{9}$/,
    placeholder: '6 71 23 45 67',
  },
  {
    code: 'GA',
    name: 'Gabon',
    dial: '+241',
    flag: '🇬🇦',
    pattern: /^\d{8}$/,
    placeholder: '06 12 34 56',
  },
  {
    code: 'CG',
    name: 'Congo',
    dial: '+242',
    flag: '🇨🇬',
    pattern: /^\d{9}$/,
    placeholder: '06 612 34 56',
  },
  {
    code: 'CD',
    name: 'RD Congo',
    dial: '+243',
    flag: '🇨🇩',
    pattern: /^\d{9}$/,
    placeholder: '81 234 56 78',
  },
  {
    code: 'MA',
    name: 'Maroc',
    dial: '+212',
    flag: '🇲🇦',
    pattern: /^\d{9}$/,
    placeholder: '6 12 34 56 78',
  },
  {
    code: 'TN',
    name: 'Tunisie',
    dial: '+216',
    flag: '🇹🇳',
    pattern: /^\d{8}$/,
    placeholder: '20 12 34 56',
  },
  {
    code: 'DZ',
    name: 'Algérie',
    dial: '+213',
    flag: '🇩🇿',
    pattern: /^\d{9}$/,
    placeholder: '5 12 34 56 78',
  },
  {
    code: 'FR',
    name: 'France',
    dial: '+33',
    flag: '🇫🇷',
    pattern: /^\d{9}$/,
    placeholder: '6 12 34 56 78',
  },
  {
    code: 'BE',
    name: 'Belgique',
    dial: '+32',
    flag: '🇧🇪',
    pattern: /^\d{8,9}$/,
    placeholder: '470 12 34 56',
  },
  {
    code: 'US',
    name: 'États-Unis',
    dial: '+1',
    flag: '🇺🇸',
    pattern: /^\d{10}$/,
    placeholder: '202 555 0123',
  },
  {
    code: 'GB',
    name: 'Royaume-Uni',
    dial: '+44',
    flag: '🇬🇧',
    pattern: /^\d{10}$/,
    placeholder: '7911 123456',
  },
];
