/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddRelationshipRequest { 
    /**
     * One of: Spouse, Child, Dependent, Guarantor, Proxy, Parent, Sibling, Other
     */
    type?: AddRelationshipRequestTypeEnum;
    relatedClientId?: string | null;
    externalFullName?: string | null;
    externalPhoneNumber?: string | null;
    externalDateOfBirth?: string | null;
    externalDocumentNumber?: string | null;
}
export enum AddRelationshipRequestTypeEnum {
    Spouse = 'Spouse',
    Child = 'Child',
    Dependent = 'Dependent',
    Guarantor = 'Guarantor',
    Proxy = 'Proxy',
    Parent = 'Parent',
    Sibling = 'Sibling',
    Other = 'Other'
};



