/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BeneficialOwnerDto { 
    id?: string;
    linkedClientId?: string | null;
    linkedClientNumber?: string | null;
    linkedClientDisplayName?: string | null;
    externalFullName?: string | null;
    externalNationality?: string | null;
    externalDateOfBirthMasked?: string | null;
    externalDocumentNumberMasked?: string | null;
    ownershipPercentage?: number;
    controlType?: string | null;
    validFrom?: string;
    validTo?: string | null;
    isActive?: boolean;
}

