/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaptureLeadRequest { 
    fullName?: string | null;
    phoneNumber?: string | null;
    /**
     * One of: Web, MobileAgent, Agency, CallCenter, Sms, Ussd, WhatsApp, Referral, Partner, FileImport, Campaign
     */
    source?: CaptureLeadRequestSourceEnum;
    interestedProduct?: string | null;
    preferredLanguage?: string | null;
    latitude?: number;
    longitude?: number;
    preferredAgencyId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    /**
     * One of: Unknown, Male, Female, Other
     */
    gender?: CaptureLeadRequestGenderEnum | null;
    dateOfBirth?: string | null;
    desiredAmount?: number | null;
    desiredCurrency?: string | null;
    campaign?: string | null;
    /**
     * One of: Web, MobileAgent, Agency, CallCenter, Sms, Ussd, WhatsApp, Referral, Partner, Import, MarketingCampaign
     */
    channel?: CaptureLeadRequestChannelEnum | null;
    comment?: string | null;
    externalReference?: string | null;
    ownerId?: string | null;
    agencyId?: string | null;
    agentCollectedLeadId?: string | null;
    companyName?: string | null;
    companyEmail?: string | null;
    companyPhone?: string | null;
    website?: string | null;
    /**
     * One of: Individual, Corporate
     */
    prospectType?: CaptureLeadRequestProspectTypeEnum | null;
    nationalId?: string | null;
    customerReference?: string | null;
    /**
     * One of: Block, Warn
     */
    gateMode?: CaptureLeadRequestGateModeEnum | null;
    minConfidenceThreshold?: number | null;
    force?: boolean;
    leadSourceConfigId?: string | null;
}
export enum CaptureLeadRequestSourceEnum {
    Web = 'Web',
    MobileAgent = 'MobileAgent',
    Agency = 'Agency',
    CallCenter = 'CallCenter',
    Sms = 'Sms',
    Ussd = 'Ussd',
    WhatsApp = 'WhatsApp',
    Referral = 'Referral',
    Partner = 'Partner',
    FileImport = 'FileImport',
    Campaign = 'Campaign'
};
export enum CaptureLeadRequestGenderEnum {
    Unknown = 'Unknown',
    Male = 'Male',
    Female = 'Female',
    Other = 'Other'
};
export enum CaptureLeadRequestChannelEnum {
    Web = 'Web',
    MobileAgent = 'MobileAgent',
    Agency = 'Agency',
    CallCenter = 'CallCenter',
    Sms = 'Sms',
    Ussd = 'Ussd',
    WhatsApp = 'WhatsApp',
    Referral = 'Referral',
    Partner = 'Partner',
    Import = 'Import',
    MarketingCampaign = 'MarketingCampaign'
};
export enum CaptureLeadRequestProspectTypeEnum {
    Individual = 'Individual',
    Corporate = 'Corporate'
};
export enum CaptureLeadRequestGateModeEnum {
    Block = 'Block',
    Warn = 'Warn'
};



