/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConsentDto { 
    id?: string;
    leadId?: string;
    type?: string | null;
    channel?: string | null;
    status?: string | null;
    grantedAt?: string;
    proofReference?: string | null;
    recordedBy?: string;
    withdrawnAt?: string | null;
    withdrawnBy?: string | null;
    withdrawalReason?: string | null;
}

