/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserRequest { 
    agencyId?: string;
    roleId?: string;
    fullName?: string | null;
    email?: string | null;
    defaultLanguage?: string | null;
    spokenLanguages?: Array<string> | null;
    specialties?: Array<string> | null;
}

