/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostalAddressInput } from './postal-address-input.interface';


export interface CreateLegalClientRequest { 
    agencyId?: string;
    advisorUserId?: string | null;
    legalName?: string | null;
    legalFormCode?: string | null;
    registrationNumber?: string | null;
    taxIdNumber?: string | null;
    incorporationDate?: string;
    headOfficeAddress?: PostalAddressInput;
    phoneNumbers?: Array<string> | null;
    email?: string | null;
    preferredLanguage?: string | null;
}

