/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostalAddressInput } from './postal-address-input.interface';


export interface CreateIndividualClientRequest { 
    agencyId?: string;
    advisorUserId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    maidenName?: string | null;
    /**
     * One of: Male, Female, Other
     */
    gender?: CreateIndividualClientRequestGenderEnum;
    dateOfBirth?: string;
    birthPlace?: string | null;
    nationality?: string | null;
    /**
     * One of: Single, Married, Divorced, Widowed, FreeUnion
     */
    maritalStatus?: CreateIndividualClientRequestMaritalStatusEnum | null;
    fatherName?: string | null;
    motherName?: string | null;
    profession?: string | null;
    employer?: string | null;
    declaredIncome?: number | null;
    declaredIncomeCurrency?: string | null;
    preferredLanguage?: string | null;
    /**
     * One of: NationalIdCard, Passport, DriverLicense, ConsularCard, VoterCard, ResidencePermit, Other
     */
    identityDocumentType?: CreateIndividualClientRequestIdentityDocumentTypeEnum;
    identityDocumentNumber?: string | null;
    identityDocumentIssuedOn?: string | null;
    identityDocumentExpiresOn?: string | null;
    phoneNumbers?: Array<string> | null;
    email?: string | null;
    address?: PostalAddressInput;
    confirmNoDuplicate?: boolean;
}
export enum CreateIndividualClientRequestGenderEnum {
    Male = 'Male',
    Female = 'Female',
    Other = 'Other'
};
export enum CreateIndividualClientRequestMaritalStatusEnum {
    Single = 'Single',
    Married = 'Married',
    Divorced = 'Divorced',
    Widowed = 'Widowed',
    FreeUnion = 'FreeUnion'
};
export enum CreateIndividualClientRequestIdentityDocumentTypeEnum {
    NationalIdCard = 'NationalIdCard',
    Passport = 'Passport',
    DriverLicense = 'DriverLicense',
    ConsularCard = 'ConsularCard',
    VoterCard = 'VoterCard',
    ResidencePermit = 'ResidencePermit',
    Other = 'Other'
};



