/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateKycFileRequest { 
    customerId?: string;
    /**
     * One of: Agency, MobileAgent, Web, Import, LeadConversion
     */
    channel?: CreateKycFileRequestChannelEnum | null;
    /**
     * One of: Low, Standard, High
     */
    vigilanceLevel?: CreateKycFileRequestVigilanceLevelEnum | null;
}
export enum CreateKycFileRequestChannelEnum {
    Agency = 'Agency',
    MobileAgent = 'MobileAgent',
    Web = 'Web',
    Import = 'Import',
    LeadConversion = 'LeadConversion'
};
export enum CreateKycFileRequestVigilanceLevelEnum {
    Low = 'Low',
    Standard = 'Standard',
    High = 'High'
};



