/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DispatchLeadRequest { 
    /**
     * One of: RoundRobin, WeightedRoundRobin, CherryPicking, CompatibilityScoring, StickyAssignment
     */
    strategy?: DispatchLeadRequestStrategyEnum;
}
export enum DispatchLeadRequestStrategyEnum {
    RoundRobin = 'RoundRobin',
    WeightedRoundRobin = 'WeightedRoundRobin',
    CherryPicking = 'CherryPicking',
    CompatibilityScoring = 'CompatibilityScoring',
    StickyAssignment = 'StickyAssignment'
};



