/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngestionDto { 
    id?: string;
    ingestedAt?: string;
    externalId?: string | null;
    /**
     * One of: Accepted, Rejected, Duplicate, Failed
     */
    status?: IngestionDtoStatusEnum;
    rejectionReason?: string | null;
    leadId?: string;
}
export enum IngestionDtoStatusEnum {
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    Duplicate = 'Duplicate',
    Failed = 'Failed'
};



