/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KycFileListItem { 
    kycFileId?: string;
    customerId?: string;
    agencyId?: string | null;
    status?: string | null;
    tier?: string | null;
    vigilanceLevel?: string | null;
    confidenceScore?: number | null;
    duplicateSuspected?: boolean;
    requiredActionCode?: string | null;
    awaitingMe?: boolean;
    updatedAt?: string;
}

