/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KycFileDto { 
    id?: string;
    customerId?: string;
    status?: string | null;
    tier?: string | null;
    channel?: string | null;
    vigilanceLevel?: string | null;
    confidenceScore?: number | null;
    confidenceLevel?: string | null;
    duplicateSuspected?: boolean;
    faceMatchAttempts?: number;
    nextReviewDate?: string | null;
    validatedAt?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

