/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KycCapsUsageDto } from './kyc-caps-usage-dto.interface';


export interface KycCapsDto { 
    customerId?: string;
    kycFileId?: string;
    tier?: string | null;
    isCapped?: boolean;
    currency?: string | null;
    balanceCap?: number | null;
    flowCap?: number | null;
    flowWindowDays?: number | null;
    alertPct?: number | null;
    usage?: KycCapsUsageDto;
}

