/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KycDocumentDto { 
    id?: string | null;
    kind?: string | null;
    storageRef?: string | null;
    contentType?: string | null;
    sizeBytes?: number | null;
    sha256?: string | null;
    uploadedBy?: string | null;
    uploadedAt?: string;
    reviewDecision?: string | null;
    reviewedBy?: string | null;
    reviewedAt?: string | null;
    refusalReason?: string | null;
    isCurrentForKind?: boolean;
    hasOcrReading?: boolean;
}

