/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LeadSourceDto { 
    id?: string;
    tenantId?: string;
    code?: string | null;
    label?: string | null;
    description?: string | null;
    isActive?: boolean;
    isSystem?: boolean;
    displayOrder?: number;
    createdAt?: string;
}

