/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Money } from './money.interface';


export interface LeadSourceListDto { 
    id?: string;
    code?: string | null;
    label?: string | null;
    description?: string | null;
    /**
     * One of: WebForm, InboundWebhook, ExternalApiPull, FacebookLeadAds, InstagramLeadAds, LinkedInLeadGen, WhatsAppInbound, SocialEngagement, MobileAgent, WalkIn, SmsUssdCampaign, Referral, FileImport, InboundCall
     */
    channelType?: LeadSourceListDtoChannelTypeEnum;
    /**
     * One of: EmbeddedScript, ServerWebhook, ScheduledPull, PlatformConnection, SocialTracking, Internal
     */
    mode?: LeadSourceListDtoModeEnum;
    /**
     * One of: Draft, Testing, Active, Paused, Error, Archived
     */
    status?: LeadSourceListDtoStatusEnum;
    /**
     * One of: Ok, Stale, Error
     */
    health?: LeadSourceListDtoHealthEnum;
    lastReceivedAt?: string | null;
    volume7Days?: number;
    costPerLead?: Money;
    isSystem?: boolean;
    displayOrder?: number;
    version?: number;
    createdAt?: string;
}
export enum LeadSourceListDtoChannelTypeEnum {
    WebForm = 'WebForm',
    InboundWebhook = 'InboundWebhook',
    ExternalApiPull = 'ExternalApiPull',
    FacebookLeadAds = 'FacebookLeadAds',
    InstagramLeadAds = 'InstagramLeadAds',
    LinkedInLeadGen = 'LinkedInLeadGen',
    WhatsAppInbound = 'WhatsAppInbound',
    SocialEngagement = 'SocialEngagement',
    MobileAgent = 'MobileAgent',
    WalkIn = 'WalkIn',
    SmsUssdCampaign = 'SmsUssdCampaign',
    Referral = 'Referral',
    FileImport = 'FileImport',
    InboundCall = 'InboundCall'
};
export enum LeadSourceListDtoModeEnum {
    EmbeddedScript = 'EmbeddedScript',
    ServerWebhook = 'ServerWebhook',
    ScheduledPull = 'ScheduledPull',
    PlatformConnection = 'PlatformConnection',
    SocialTracking = 'SocialTracking',
    Internal = 'Internal'
};
export enum LeadSourceListDtoStatusEnum {
    Draft = 'Draft',
    Testing = 'Testing',
    Active = 'Active',
    Paused = 'Paused',
    Error = 'Error',
    Archived = 'Archived'
};
export enum LeadSourceListDtoHealthEnum {
    Ok = 'Ok',
    Stale = 'Stale',
    Error = 'Error'
};



