/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NurturingStepDto } from './nurturing-step-dto.interface';


export interface NurturingSequenceDto { 
    id?: string;
    name?: string | null;
    description?: string | null;
    isActive?: boolean;
    createdAt?: string;
    steps?: Array<NurturingStepDto> | null;
}

