/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Money } from './money.interface';


export interface OpportunityDto { 
    id?: string;
    leadId?: string | null;
    customerEntityType?: string | null;
    customerEntityId?: string | null;
    title?: string | null;
    description?: string | null;
    product?: string | null;
    estimatedAmount?: Money;
    /**
     * One of: Prospecting, Qualification, NeedsAnalysis, Proposal, Negotiation, ClosedWon, ClosedLost
     */
    stage?: OpportunityDtoStageEnum;
    probability?: number;
    expectedCloseDate?: string | null;
    ownerId?: string | null;
    createdAt?: string;
    updatedAt?: string;
    closedAt?: string | null;
    closeReason?: string | null;
}
export enum OpportunityDtoStageEnum {
    Prospecting = 'Prospecting',
    Qualification = 'Qualification',
    NeedsAnalysis = 'NeedsAnalysis',
    Proposal = 'Proposal',
    Negotiation = 'Negotiation',
    ClosedWon = 'ClosedWon',
    ClosedLost = 'ClosedLost'
};



