/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PipelineCard { 
    id?: string;
    fullName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    interestedProduct?: string | null;
    score?: number;
    intentLevel?: string | null;
    ownerId?: string | null;
    createdAt?: string;
    lastActivityAt?: string | null;
    updatedAt?: string;
}

