/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RuleInput } from './rule-input.interface';


export interface QuestionInput { 
    label?: string | null;
    /**
     * One of: YesNo, SingleChoice, MultiChoice, Numeric, Text
     */
    type?: QuestionInputTypeEnum;
    weight?: number;
    isRequired?: boolean;
    options?: Array<string> | null;
    helpText?: string | null;
    placeholderText?: string | null;
    minValue?: number | null;
    maxValue?: number | null;
    rules?: Array<RuleInput> | null;
}
export enum QuestionInputTypeEnum {
    YesNo = 'YesNo',
    SingleChoice = 'SingleChoice',
    MultiChoice = 'MultiChoice',
    Numeric = 'Numeric',
    Text = 'Text'
};



