/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestClientExportRequest { 
    clientNumber?: string | null;
    phone?: string | null;
    identityDocumentNumber?: string | null;
    name?: string | null;
    status?: RequestClientExportRequestStatusEnum | null;
    agencyId?: string | null;
    advisorUserId?: string | null;
    type?: RequestClientExportRequestTypeEnum | null;
    segmentCode?: string | null;
}
export enum RequestClientExportRequestStatusEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5
};
export enum RequestClientExportRequestTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1
};



