/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolePermissionDto } from './role-permission-dto.interface';


export interface RoleDetailDto { 
    id?: string;
    name?: string | null;
    label?: string | null;
    isSystem?: boolean;
    isAssignable?: boolean;
    tenantId?: string | null;
    permissions?: Array<RolePermissionDto> | null;
}

