/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RuleInput { 
    triggerQuestionId?: string;
    triggerValue?: string | null;
    /**
     * One of: Show, Hide, Require
     */
    action?: RuleInputActionEnum;
}
export enum RuleInputActionEnum {
    Show = 'Show',
    Hide = 'Hide',
    Require = 'Require'
};



