/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RunDto { 
    id?: string;
    /**
     * One of: Scheduled, ManualPull, DryRun, InstallCheck
     */
    runType?: RunDtoRunTypeEnum;
    /**
     * One of: Running, Completed, Failed
     */
    status?: RunDtoStatusEnum;
    startedAt?: string;
    completedAt?: string | null;
    fetchedCount?: number;
    ingestedCount?: number;
    rejectedCount?: number;
    duplicateCount?: number;
    errorMessage?: string | null;
}
export enum RunDtoRunTypeEnum {
    Scheduled = 'Scheduled',
    ManualPull = 'ManualPull',
    DryRun = 'DryRun',
    InstallCheck = 'InstallCheck'
};
export enum RunDtoStatusEnum {
    Running = 'Running',
    Completed = 'Completed',
    Failed = 'Failed'
};



