/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceQualityDto { 
    sourceId?: string;
    code?: string | null;
    label?: string | null;
    received?: number;
    rejected?: number;
    duplicates?: number;
    contacted?: number;
    converted?: number;
    totalCost?: number;
    costCurrency?: string | null;
    costPerConvertedLead?: number | null;
}

