/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceSettings { 
    schemaVersion?: number;
    /**
     * One of: EmbeddedScript, ServerWebhook, ScheduledPull, PlatformConnection, SocialTracking, Internal
     */
    readonly expectedMode?: SourceSettingsExpectedModeEnum;
}
export enum SourceSettingsExpectedModeEnum {
    EmbeddedScript = 'EmbeddedScript',
    ServerWebhook = 'ServerWebhook',
    ScheduledPull = 'ScheduledPull',
    PlatformConnection = 'PlatformConnection',
    SocialTracking = 'SocialTracking',
    Internal = 'Internal'
};



