/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceCount { 
    /**
     * One of: Web, MobileAgent, Agency, CallCenter, Sms, Ussd, WhatsApp, Referral, Partner, FileImport, Campaign
     */
    source?: SourceCountSourceEnum;
    count?: number;
}
export enum SourceCountSourceEnum {
    Web = 'Web',
    MobileAgent = 'MobileAgent',
    Agency = 'Agency',
    CallCenter = 'CallCenter',
    Sms = 'Sms',
    Ussd = 'Ussd',
    WhatsApp = 'WhatsApp',
    Referral = 'Referral',
    Partner = 'Partner',
    FileImport = 'FileImport',
    Campaign = 'Campaign'
};



