/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskGenerationRuleDto { 
    id?: string;
    tenantId?: string;
    triggerEventType?: string | null;
    /**
     * One of: FirstContact, Qualification, SlaFollowUp, ScoreReview, OwnerHandover, ManualDispatch, Generic
     */
    taskType?: TaskGenerationRuleDtoTaskTypeEnum;
    /**
     * One of: Low, Medium, High, Critical
     */
    priority?: TaskGenerationRuleDtoPriorityEnum;
    titleTemplate?: string | null;
    descriptionTemplate?: string | null;
    slaDuration?: string;
    dueDuration?: string;
    isActive?: boolean;
    createdAt?: string;
}
export enum TaskGenerationRuleDtoTaskTypeEnum {
    FirstContact = 'FirstContact',
    Qualification = 'Qualification',
    SlaFollowUp = 'SlaFollowUp',
    ScoreReview = 'ScoreReview',
    OwnerHandover = 'OwnerHandover',
    ManualDispatch = 'ManualDispatch',
    Generic = 'Generic'
};
export enum TaskGenerationRuleDtoPriorityEnum {
    Low = 'Low',
    Medium = 'Medium',
    High = 'High',
    Critical = 'Critical'
};



