/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StepStatsDto } from './step-stats-dto.interface';


export interface TemplateStatsDto { 
    templateId?: string;
    entityType?: string | null;
    templateName?: string | null;
    version?: number;
    totalInstances?: number;
    byStatus?: { [key: string]: number; } | null;
    avgCompletionHours?: number | null;
    slaBreachCount?: number;
    stepStats?: Array<StepStatsDto> | null;
}

