/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransitionDto { 
    id?: string;
    fromStateId?: string;
    toStateId?: string | null;
    eventCode?: string | null;
    /**
     * One of: Pending, InProgress, Completed, Rejected, Cancelled, TimedOut, WaitingForChild
     */
    toTerminalStatus?: TransitionDtoToTerminalStatusEnum | null;
    priority?: number;
    conditionJson?: string | null;
    isAutoGenerated?: boolean;
}
export enum TransitionDtoToTerminalStatusEnum {
    Pending = 'Pending',
    InProgress = 'InProgress',
    Completed = 'Completed',
    Rejected = 'Rejected',
    Cancelled = 'Cancelled',
    TimedOut = 'TimedOut',
    WaitingForChild = 'WaitingForChild'
};



