/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostalAddressInput } from './postal-address-input.interface';


export interface UpdateClientSensitiveRequest { 
    expectedVersion?: number;
    reason?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    maidenName?: string | null;
    identityDocumentType?: UpdateClientSensitiveRequestIdentityDocumentTypeEnum | null;
    identityDocumentNumber?: string | null;
    identityDocumentIssuedOn?: string | null;
    identityDocumentExpiresOn?: string | null;
    address?: PostalAddressInput;
}
export enum UpdateClientSensitiveRequestIdentityDocumentTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
};



