/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateClientRequest { 
    expectedVersion?: number;
    profession?: string | null;
    employer?: string | null;
    /**
     * One of: Single, Married, Divorced, Widowed, FreeUnion
     */
    maritalStatus?: UpdateClientRequestMaritalStatusEnum | null;
    declaredIncome?: number | null;
    declaredIncomeCurrency?: string | null;
    preferredLanguage?: string | null;
}
export enum UpdateClientRequestMaritalStatusEnum {
    Single = 'Single',
    Married = 'Married',
    Divorced = 'Divorced',
    Widowed = 'Widowed',
    FreeUnion = 'FreeUnion'
};



