/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateLeadRequest { 
    fullName?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    /**
     * One of: Unknown, Male, Female, Other
     */
    gender?: UpdateLeadRequestGenderEnum | null;
    dateOfBirth?: string | null;
    interestedProduct?: string | null;
    desiredAmount?: number | null;
    desiredCurrency?: string | null;
    preferredLanguage?: string | null;
    campaign?: string | null;
    comment?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    preferredAgencyId?: string | null;
    expectedUpdatedAt?: string | null;
}
export enum UpdateLeadRequestGenderEnum {
    Unknown = 'Unknown',
    Male = 'Male',
    Female = 'Female',
    Other = 'Other'
};



