/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateAgencyRequest { 
    name?: string | null;
    description?: string | null;
    /**
     * One of: HeadQuarter, Branch, ServicePoint, Counter
     */
    agencyType?: UpdateAgencyRequestAgencyTypeEnum;
    addressStreet?: string | null;
    addressCity?: string | null;
    addressState?: string | null;
    addressCountry?: string | null;
    addressZipCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
}
export enum UpdateAgencyRequestAgencyTypeEnum {
    HeadQuarter = 'HeadQuarter',
    Branch = 'Branch',
    ServicePoint = 'ServicePoint',
    Counter = 'Counter'
};



