/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WebFormFieldDto } from './web-form-field-dto.interface';


export interface WebFormResponse { 
    fields?: Array<WebFormFieldDto> | null;
    consentText?: string | null;
    consentVersion?: string | null;
    theme?: string | null;
    submitLabel?: string | null;
    captchaProvider?: string | null;
}

