/**
 * Sankore.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkflowInstanceStepDto } from './workflow-instance-step-dto.interface';


export interface WorkflowInstanceDto { 
    id?: string;
    tenantId?: string;
    templateId?: string;
    entityType?: string | null;
    entityId?: string;
    status?: string | null;
    currentStepOrder?: number;
    totalSteps?: number;
    startedByUserId?: string;
    startedAt?: string;
    completedAt?: string | null;
    steps?: Array<WorkflowInstanceStepDto> | null;
}

