export * from './agencies.service';
import { AgenciesApiService } from './agencies.service';
export * from './audit.service';
import { AuditApiService } from './audit.service';
export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './bootstrap.service';
import { BootstrapApiService } from './bootstrap.service';
export * from './company-info.service';
import { CompanyInfoApiService } from './company-info.service';
export * from './delivery-logs.service';
import { DeliveryLogsApiService } from './delivery-logs.service';
export * from './email-templates.service';
import { EmailTemplatesApiService } from './email-templates.service';
export * from './health.service';
import { HealthApiService } from './health.service';
export * from './leads.service';
import { LeadsApiService } from './leads.service';
export * from './notification-settings.service';
import { NotificationSettingsApiService } from './notification-settings.service';
export * from './permissions.service';
import { PermissionsApiService } from './permissions.service';
export * from './products.service';
import { ProductsApiService } from './products.service';
export * from './roles.service';
import { RolesApiService } from './roles.service';
export * from './territories.service';
import { TerritoriesApiService } from './territories.service';
export * from './users.service';
import { UsersApiService } from './users.service';
export * from './webhooks.service';
import { WebhooksApiService } from './webhooks.service';
export * from './workflow.service';
import { WorkflowApiService } from './workflow.service';
export * from './workflow-instances.service';
import { WorkflowInstancesApiService } from './workflow-instances.service';
export * from './workflow-templates.service';
import { WorkflowTemplatesApiService } from './workflow-templates.service';
export const APIS = [AgenciesApiService, AuditApiService, AuthApiService, BootstrapApiService, CompanyInfoApiService, DeliveryLogsApiService, EmailTemplatesApiService, HealthApiService, LeadsApiService, NotificationSettingsApiService, PermissionsApiService, ProductsApiService, RolesApiService, TerritoriesApiService, UsersApiService, WebhooksApiService, WorkflowApiService, WorkflowInstancesApiService, WorkflowTemplatesApiService];
